version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      - mynetwork
    ports:
      - "8080:8080"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    networks:
      - mynetwork

networks:
  mynetwork:
